# Use root/example as user/password credentials
version: "3.7"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "/Users/dexter/data/db:/data/db"
    container_name: mongodb-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
