version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-alpine-py
    ports:
      - "9000:8080"
    volumes:
      - "~/temp/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:
