# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "/data/postgre/:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgretest
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
